# Generated by Django 2.2 on 2023-09-23 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('product_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invApp.Products')),
            ],
        ),
    ]
