# Generated by Django 2.2 on 2023-09-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0002_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='id',
        ),
        migrations.AddField(
            model_name='sales',
            name='transaction_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
